import json, sys
for lang in ("ja", "ko"):
    m = json.load(open(f"model_{lang}.json", encoding="utf-8"))
    lines = "\n".join(f"{k}\t{','.join(map(str, v))}" for k, v in m["w"].items())
    src = (f"// Auto-generated by tools/cjk/build_cjk_model.py from model_{lang}.json. Do not edit.\n"
           f"// Character-context boundary model for punctuation-free {lang} ASR (O / comma / sentence end).\n"
           f"export default {{ lang: {json.dumps(lang)}, scale: {m['scale']}, bias: {json.dumps(m['bias'])}, weights: {json.dumps(lines, ensure_ascii=False)} }};\n")
    open(f"../../src/function/asrModel{lang.capitalize()}.mjs", "w", encoding="utf-8").write(src)
    print(lang, len(src.encode()))
