import json, sys
m = json.load(open(sys.argv[1] if len(sys.argv)>1 else "model.json"))
lines = "\n".join(f"{k}\t{','.join(map(str,v))}" for k,v in m["w"].items())
src = ("// Auto-generated by tools/build_model.py from tools/model.json. Do not edit.\n"
       "// Tiny punctuation-boundary model (O / comma / period) trained on IWSLT2012 TED transcripts.\n"
       f"export default {{ scale: {m['scale']}, bias: {json.dumps(m['bias'])}, vocab: {json.dumps(' '.join(m['vocab']))}, lexicon: {json.dumps(' '.join(f'{w}/{t}' for w,t in m['lex'].items()))}, weights: {json.dumps(lines)} }};\n")
open("src/function/asrBoundaryModel.mjs","w").write(src)
print(len(src))
